version: '3.8'

services:
  api:
    build: .
    container_name: credit-risk-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=models/credit_risk_model.joblib
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    
  # Uncomment and configure these additional services as needed
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - redis_data:/data
  
  # postgres:
  #   image: postgres:13-alpine
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #     - POSTGRES_DB=credit_risk
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

# volumes:
#   redis_data:
#   postgres_data:
